// ── tier-gate ────────────────────────────────────────────────────────────────────────────
// access-tier-ask-plan.md §4 / D2. Sits between Aggregate and If4 on the promotion lane and
// decides whether the tier is RESOLVABLE — stated by the customer (the parser fork emits
// TIER TOKENS in access_levels), or the contact is entitled to exactly one tier. If4 reads
// `tier_proceed`; FALSE routes to access-level-choice-message (the tier ask, or the
// no-access message when name[] is empty).
//
// This node is ALSO the single place the tier×brand→compound recomposition happens
// (plan §3): `access_levels_recomposed` is what Call 'sub-get-results' sends to the CRM
// (semantic_input + user_prompt both read it), and disallowed-entity-gate's Q23 held-check
// reads `tier_stated` / `entitled_tiers` / `brand_gate_empty` / `brand_unheld` / `query_brands`.
//
// The block between the markers is a BYTE-COPY of tests/offline/access-tier/mapper.js
// (source of truth — 49/49 probe, 13/13 mutations; probe.js EB-* enforces byte identity).
// When the CRM ships additive brands[]/tiers[] on the entitlement read, this node consumes
// them instead and the mapper block is deleted (plan D8).
// >>> mapper-embed (generated by gen-embeds.js — DO NOT EDIT BY HAND)
const BRANDS = ['sorento', 'cabana', 'mocha'];

function parseLevel(name) {
  const s = String(name ?? '').trim().toLowerCase().replace(/\s+/g, ' ');
  if (s === 'end user' || s === 'enduser' || s === 'end-user') return { brand: null, tier: 'end_user' };
  const m = s.match(/^(sorento|cabana|mocha) (dealer|office)$/);
  return m ? { brand: m[1], tier: m[2] } : null;
}

function mapEntitlement(names) {
  const brands = new Set(), tiers = new Set(), unknown = [];
  for (const n of (Array.isArray(names) ? names : [])) {
    const p = parseLevel(n);
    if (!p) { if (String(n ?? '').trim()) unknown.push(String(n)); continue; }
    if (p.brand) brands.add(p.brand);
    tiers.add(p.tier);
  }
  const TIER_ORDER = ['dealer', 'office', 'end_user'];
  return {
    brands: BRANDS.filter(b => brands.has(b)),
    tiers: TIER_ORDER.filter(t => tiers.has(t)),
    unknown,
  };
}

function recompose(tiers, queryBrands, entitled) {
  const want = new Set((Array.isArray(tiers) ? tiers : []).map(t => String(t ?? '').trim().toLowerCase()));
  const qb = (Array.isArray(queryBrands) ? queryBrands : [])
    .map(b => String(b ?? '').trim().toLowerCase()).filter(b => BRANDS.includes(b));
  const ent = Array.isArray(entitled) ? entitled : [];
  const entMap = mapEntitlement(ent);
  // "unheld" is only a meaningful claim when the contact HAS brand-scoped entitlement to compare
  // against. entMap.brands empty ⇒ no brand axis for this contact ⇒ nothing to deny (R10/R11).
  const brandUnheld = qb.length > 0 && entMap.brands.length > 0 && !qb.some(b => entMap.brands.includes(b));
  // unheld ⇒ allow NO brand-scoped name (probe R5): falling back to the full entitlement here would
  // silently answer a Cabana ask with Sorento files — the exact widen the flag exists to stop.
  const allowBrands = qb.length
    ? (brandUnheld ? [] : qb.filter(b => entMap.brands.includes(b)))
    : entMap.brands;
  const out = [];
  for (const n of ent) {
    const p = parseLevel(n);
    if (!p || !want.has(p.tier)) continue;
    // end_user is brandless TODAY: include it whenever its tier was chosen. When the CRM's
    // brand-scoping decision for end_user lands (contract §3 item 3), this branch follows it.
    if (p.brand && !allowBrands.includes(p.brand)) continue;
    if (!out.includes(n)) out.push(n);
  }
  // F5: a surviving BRANDLESS level (End User is unbranded today) COVERS every brand, including the
  // one the customer named — so claiming they lack it is simply false. Measured: a contact was told
  // "You don't have access to cabana promotions" and handed Cabana End User files in the same reply.
  // `brand_unheld` drives a NOTICE, and a notice is a factual claim; only make it when nothing we
  // are about to send covers the named brand.
  const servedBrandless = out.some(n => { const p = parseLevel(n); return p && !p.brand; });
  const unheldClaim = brandUnheld && !servedBrandless;
  // Suppress ONLY when the denial left nothing to send. If a brandless level survived, the contact
  // still has something they may legitimately see: notice AND answer (the Q23 shape), never notice
  // and silence.
  return { access_levels: out, brand_gate_empty: brandUnheld && out.length === 0, brand_unheld: unheldClaim };
}

function needsTierAsk(domain, stated, entitledTiers, opts) {
  if (domain !== 'promotion') return false;
  if (opts && opts.brandGateEmpty === true) return false;
  if (opts && opts.pendingPick === true) return false;
  if (Array.isArray(stated) && stated.length > 0) return false;
  return (Array.isArray(entitledTiers) ? entitledTiers : []).length > 1;
}
// <<< mapper-embed

const j = $input.first().json;
const names = Array.isArray(j.name) ? j.name : [];
const parser = $("Call 'sub-query-reformulator'").first().json.output ?? {};

// stated tiers: tier tokens straight through; legacy compound names ("Sorento Dealer")
// tolerated via parseLevel so an old session or a stale parser cannot regress the gate.
const TIER_ORDER = ['dealer', 'office', 'end_user'];
const _statedSet = new Set();
for (const a of (Array.isArray(parser.access_levels) ? parser.access_levels : [])) {
  const s = String(a ?? '').trim().toLowerCase();
  if (TIER_ORDER.includes(s)) { _statedSet.add(s); continue; }
  const p = parseLevel(a);
  if (p) _statedSet.add(p.tier);
}
const tier_stated = TIER_ORDER.filter(t => _statedSet.has(t));

const entMap = mapEntitlement(names);

// brands the customer named THIS query. D9: the parser derives this now (statedBrands = brand
// entities ∪ the brand half of a COMPOUND stated level) because only the parser still has the
// RAW LLM levels — by the time they reach here they are tier tokens and the brand is gone.
// Fallback = the original entity-only scan, so an older/live parser degrades to yesterday's
// behaviour instead of throwing.
const query_brands = Array.isArray(parser.query_brands)
  ? parser.query_brands.filter(b => BRANDS.includes(String(b ?? '').toLowerCase()))
  : [...new Set((Array.isArray(parser.entities) ? parser.entities : [])
      .filter(e => String((e && e.hint) || '').toLowerCase() === 'brand')
      .map(e => BRANDS.find(v => String((e && (e.canonical_code || e.raw)) || '').toLowerCase().includes(v)))
      .filter(Boolean))];

// D11: a pick the parser ALREADY resolved outranks the ask. `_pending_pick` is the parser's own
// discriminator (roster context + "named no new scope"); the three flags beside it are
// spine-visible provenance, kept as defence in depth so a parser without `_pending_pick` still
// cannot have a customer's pick discarded (execs 12041783 / 12041879). The tier-pick answer turn
// is NOT a foreign pick — it states a tier and must proceed.
const pendingPick = parser._tier_pick_scope_reused !== true && (
  parser._pending_pick === true
  || parser._promo_pick_scope_reused === true
  || parser.dym_pick_applied === true
  || parser.member_pick_context === true);

// ── recomposition (plan §3) — the compound access_levels the CRM understands TODAY ──
// ⚠️ ORDER MATTERS, and it changed for F6: this block runs BEFORE the ask trigger, because a closed
// brand gate has to be able to CANCEL the ask. Nothing here reads tier_ask, so hoisting it leaves
// every recomposed value identical. On the ask turn tier_stated is empty, so `_chosen` is the whole
// entitled tier set — exactly the right probe for "does this contact hold the named brand at ANY
// tier", which is the question the ask must not be asked over.
const _chosen = tier_stated.length ? tier_stated : entMap.tiers;
let access_levels_recomposed, brand_gate_empty = false, brand_unheld = false;
if (_chosen.length === 0) {
  // entitlement holds no mappable tier (unknown names only): legacy full passthrough —
  // the mapper never guesses an unknown level, so the split model simply does not apply.
  access_levels_recomposed = names.slice().sort();
} else {
  const _r = recompose(_chosen, query_brands, names);
  brand_gate_empty = _r.brand_gate_empty;
  // F1: the NOTICE signal, separate from the SUPPRESSION signal. disallowed-entity-gate renders
  // from this one; only `brand_gate_empty` may suppress. Merging them told a brandless contact
  // "here's what you do have:" and then sent nothing (exec 12045520).
  brand_unheld = _r.brand_unheld;
  access_levels_recomposed = _r.access_levels;
  if (access_levels_recomposed.length === 0 && !brand_gate_empty && tier_stated.length) {
    // Q23: a stated tier the contact does not hold — answer at their REAL entitlement;
    // disallowed-entity-gate renders the notice that explains it. The brand gate does NOT
    // widen here: it sends []. ⚠️ Sending [] is a narrowing REQUEST, not the enforcement —
    // the first build claimed "[] makes the CRM return nothing" as fact and it was never
    // verified (UAC BLOCKER-2). D10 puts the actual denial in promo-picker, which suppresses
    // the answer and every attachment locally whatever the CRM returns.
    access_levels_recomposed = names.slice().sort();
  }
}

// D2 ask trigger. A zero-entitlement contact keeps the no-access lane: tier_proceed is
// false with names empty, and needsTierAsk's A5 bound means tier_ask stays false too.
// F6: `brandGateEmpty` makes the DENIAL outrank the ask. Asking "office / dealer / end user?" for a
// brand we are about to refuse both wastes the customer's turn and creates the pick turn on which
// the refusal was being lost (fork execs 12055170 → 12055181).
const tier_ask = needsTierAsk(parser.domain_hint, tier_stated, entMap.tiers, {
  pendingPick,
  brandGateEmpty: brand_gate_empty,
});
const tier_proceed = names.length > 0 && !tier_ask;

// D14: when we are about to ask, emit the per-tier probe plan. Each entry carries the compound
// names for ONE tier, from the same `recompose` the answer lane uses, so the availability probe
// asks exactly the question the customer's pick would ask. Empty off the ask lane, so every
// other turn is byte-inert.
const tier_probe_plan = tier_ask
  ? entMap.tiers.map(t => ({ tier: t, access_levels: recompose([t], query_brands, names).access_levels }))
  : [];

return {
  ...j,
  tier_stated,
  entitled_tiers: entMap.tiers,
  entitled_unknown: entMap.unknown,
  query_brands,
  pending_pick: pendingPick,
  tier_ask,
  tier_proceed,
  access_levels_recomposed,
  tier_probe_plan,
  brand_gate_empty,
  brand_unheld,
};
