#!/usr/bin/env node
// Regenerates the mapper-embed blocks in tier-gate.js / output_exchange.js from
// tests/offline/access-tier/mapper.js — the SOURCE OF TRUTH for the tier logic.
// The embeds are byte-copies by construction; probe.js EB-* re-verifies on every run,
// so a hand-edit inside the markers goes red immediately.
const fs = require('fs'), path = require('path');
const m = fs.readFileSync(path.join(__dirname, '..', 'access-tier', 'mapper.js'), 'utf8');
const slice = (n) => {
  const r = m.match(new RegExp(`function ${n}\\([^]*?\\n\\}\\n`));
  if (!r) throw new Error(`cannot slice function ${n}`);
  return r[0];
};
const cl = (n) => {
  const r = m.match(new RegExp(`const ${n} = [^\\n]*\\n`));
  if (!r) throw new Error(`cannot slice const ${n}`);
  return r[0];
};
const EMBEDS = {
  'tier-gate.js': cl('BRANDS') + '\n' + slice('parseLevel') + '\n' + slice('mapEntitlement')
    + '\n' + slice('recompose') + '\n' + slice('needsTierAsk'),
  // statedBrands added for D9: the brand half of a COMPOUND stated level is recovered here,
  // in the parser, because this is the last point where the RAW LLM levels still exist.
  'output_exchange.js': cl('BRANDS') + cl('TIER_WORDS') + '\n' + slice('parseLevel') + '\n'
    + slice('statedTiers') + '\n' + slice('statedBrands'),
};
const A = '// >>> mapper-embed (generated by gen-embeds.js — DO NOT EDIT BY HAND)';
const B = '// <<< mapper-embed';
for (const [f, mid] of Object.entries(EMBEDS)) {
  const p = path.join(__dirname, f);
  let s = fs.readFileSync(p, 'utf8');
  const i = s.indexOf(A), j = s.indexOf(B);
  if (i < 0 || j < 0 || j < i) { console.error(`${f}: markers missing`); process.exit(1); }
  s = s.slice(0, i + A.length) + '\n' + mid + s.slice(j);
  fs.writeFileSync(p, s);
  console.log(`embedded -> ${f}`);
}
