// ── tier-gate ────────────────────────────────────────────────────────────────────────────
// access-tier-ask-plan.md §4 / D2. Sits between Aggregate and If4 on the promotion lane and
// decides whether the tier is RESOLVABLE — stated by the customer (the parser fork emits
// TIER TOKENS in access_levels), or the contact is entitled to exactly one tier. If4 reads
// `tier_proceed`; FALSE routes to access-level-choice-message (the tier ask, or the
// no-access message when name[] is empty).
//
// This node is ALSO the single place the tier×brand→compound recomposition happens
// (plan §3): `access_levels_recomposed` is what Call 'sub-get-results' sends to the CRM
// (semantic_input + user_prompt both read it), and disallowed-entity-gate's Q23 held-check
// reads `tier_stated` / `entitled_tiers` / `brand_gate_empty` / `query_brands`.
//
// The block between the markers is a BYTE-COPY of tests/offline/access-tier/mapper.js
// (source of truth — 30/30 probe, 7/7 mutations; probe.js EB-* enforces byte identity).
// When the CRM ships additive brands[]/tiers[] on the entitlement read, this node consumes
// them instead and the mapper block is deleted (plan D8).
// >>> mapper-embed (generated by gen-embeds.js — DO NOT EDIT BY HAND)
const BRANDS = ['sorento', 'cabana', 'mocha'];

function parseLevel(name) {
  const s = String(name ?? '').trim().toLowerCase().replace(/\s+/g, ' ');
  if (s === 'end user' || s === 'enduser' || s === 'end-user') return { brand: null, tier: 'end_user' };
  const m = s.match(/^(sorento|cabana|mocha) (dealer|office)$/);
  return m ? { brand: m[1], tier: m[2] } : null;
}

function mapEntitlement(names) {
  const brands = new Set(), tiers = new Set(), unknown = [];
  for (const n of (Array.isArray(names) ? names : [])) {
    const p = parseLevel(n);
    if (!p) { if (String(n ?? '').trim()) unknown.push(String(n)); continue; }
    if (p.brand) brands.add(p.brand);
    tiers.add(p.tier);
  }
  const TIER_ORDER = ['dealer', 'office', 'end_user'];
  return {
    brands: BRANDS.filter(b => brands.has(b)),
    tiers: TIER_ORDER.filter(t => tiers.has(t)),
    unknown,
  };
}

function recompose(tiers, queryBrands, entitled) {
  const want = new Set((Array.isArray(tiers) ? tiers : []).map(t => String(t ?? '').trim().toLowerCase()));
  const qb = (Array.isArray(queryBrands) ? queryBrands : [])
    .map(b => String(b ?? '').trim().toLowerCase()).filter(b => BRANDS.includes(b));
  const ent = Array.isArray(entitled) ? entitled : [];
  const entMap = mapEntitlement(ent);
  const brandGateEmpty = qb.length > 0 && !qb.some(b => entMap.brands.includes(b));
  // brand_gate_empty ⇒ allow NOTHING (probe R5): falling back to the full entitlement here would
  // silently answer a Cabana ask with Sorento files — the exact widen the flag exists to stop.
  const allowBrands = qb.length
    ? (brandGateEmpty ? [] : qb.filter(b => entMap.brands.includes(b)))
    : entMap.brands;
  const out = [];
  for (const n of ent) {
    const p = parseLevel(n);
    if (!p || !want.has(p.tier)) continue;
    // end_user is brandless TODAY: include it whenever its tier was chosen. When the CRM's
    // brand-scoping decision for end_user lands (contract §3 item 3), this branch follows it.
    if (p.brand && !allowBrands.includes(p.brand)) continue;
    if (!out.includes(n)) out.push(n);
  }
  return { access_levels: out, brand_gate_empty: brandGateEmpty };
}

function needsTierAsk(domain, stated, entitledTiers) {
  if (domain !== 'promotion') return false;
  if (Array.isArray(stated) && stated.length > 0) return false;
  return (Array.isArray(entitledTiers) ? entitledTiers : []).length > 1;
}
// <<< mapper-embed

const j = $input.first().json;
const names = Array.isArray(j.name) ? j.name : [];
const parser = $("Call 'sub-query-reformulator'").first().json.output ?? {};

// stated tiers: tier tokens straight through; legacy compound names ("Sorento Dealer")
// tolerated via parseLevel so an old session or a stale parser cannot regress the gate.
const TIER_ORDER = ['dealer', 'office', 'end_user'];
const _statedSet = new Set();
for (const a of (Array.isArray(parser.access_levels) ? parser.access_levels : [])) {
  const s = String(a ?? '').trim().toLowerCase();
  if (TIER_ORDER.includes(s)) { _statedSet.add(s); continue; }
  const p = parseLevel(a);
  if (p) _statedSet.add(p.tier);
}
const tier_stated = TIER_ORDER.filter(t => _statedSet.has(t));

const entMap = mapEntitlement(names);

// brands the customer named THIS query (D6: brand arrives only as an ENTITY, never a field)
const query_brands = [...new Set((Array.isArray(parser.entities) ? parser.entities : [])
  .filter(e => String((e && e.hint) || '').toLowerCase() === 'brand')
  .map(e => BRANDS.find(v => String((e && (e.canonical_code || e.raw)) || '').toLowerCase().includes(v)))
  .filter(Boolean))];

// D2 ask trigger. A zero-entitlement contact keeps the no-access lane: tier_proceed is
// false with names empty, and needsTierAsk's A5 bound means tier_ask stays false too.
const tier_ask = needsTierAsk(parser.domain_hint, tier_stated, entMap.tiers);
const tier_proceed = names.length > 0 && !tier_ask;

// ── recomposition (plan §3) — the compound access_levels the CRM understands TODAY ──
const _chosen = tier_stated.length ? tier_stated : entMap.tiers;
let access_levels_recomposed, brand_gate_empty = false;
if (_chosen.length === 0) {
  // entitlement holds no mappable tier (unknown names only): legacy full passthrough —
  // the mapper never guesses an unknown level, so the split model simply does not apply.
  access_levels_recomposed = names.slice().sort();
} else {
  const _r = recompose(_chosen, query_brands, names);
  brand_gate_empty = _r.brand_gate_empty;
  access_levels_recomposed = _r.access_levels;
  if (access_levels_recomposed.length === 0 && !brand_gate_empty && tier_stated.length) {
    // Q23: a stated tier the contact does not hold — answer at their REAL entitlement;
    // disallowed-entity-gate renders the notice that explains it. brand_gate_empty stays
    // FAIL-CLOSED (probe R5): [] makes the CRM return nothing, never a silent widen.
    access_levels_recomposed = names.slice().sort();
  }
}

return {
  ...j,
  tier_stated,
  entitled_tiers: entMap.tiers,
  entitled_unknown: entMap.unknown,
  query_brands,
  tier_ask,
  tier_proceed,
  access_levels_recomposed,
  brand_gate_empty,
};
