#!/usr/bin/env python3
"""repin-manifest.py — re-record MANIFEST node hashes after a DELIBERATE local body edit.

WHY THIS EXISTS
    MANIFEST.json carries two independent guarantees:
      * versionId            — "this export is the live workflow at version X" (export-workflows.py --verify)
      * nodes[*].sha256      — "these nodes/*.js files are the bytes this export shipped" (tests/offline/node-source.js)
    The second one is what stops a stale hand-copy being tested instead of the real body (LESSONS §76).
    But under the git-first flow (plans/test-pyramid-and-git-deploy.md) you EDIT nodes/*.js on purpose
    and then deploy them. Without a way to re-record the hash, node-source.js exits 2 with "the export
    is corrupt" and the whole suite dies — i.e. the integrity gate makes the intended workflow impossible.

    This script re-records ONLY the sha side. versionId is left ALONE on purpose: it still means
    "the live version this edit is based on", so `--verify` keeps detecting live drift underneath you,
    and deploy.py gate (c) keeps refusing to deploy onto a workflow that moved.

    It is deliberately a SEPARATE, EXPLICIT command rather than something assemble.py does silently:
    an accidental corruption and an intended edit look identical to a hash check, so the difference
    has to be a human saying which it is.

USAGE
    repin-manifest.py <slug> [--check]
      --check   report drift and exit 1 if any node body differs from its recorded sha (no writes)
"""
import argparse, hashlib, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]

def sha256(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("slug")
    ap.add_argument("--check", action="store_true",
                    help="report drift and exit 1 instead of re-recording")
    a = ap.parse_args()

    d = ROOT / "export" / a.slug
    mp = d / "MANIFEST.json"
    if not mp.exists():
        print(f"FATAL: {mp} missing — run export-workflows.py first", file=sys.stderr)
        return 2
    man = json.loads(mp.read_text())

    drift, missing = [], []
    for name, rec in man.get("nodes", {}).items():
        f = d / "nodes" / (rec["file"] if isinstance(rec, dict) else f"{name}.js")
        if not f.exists():
            missing.append(name)
            continue
        body = f.read_bytes()
        have = sha256(body)
        want = rec.get("sha256") if isinstance(rec, dict) else rec
        if have != want:
            drift.append((name, want, have, len(body.decode("utf8").splitlines())))

    if missing:
        print("FATAL: node file(s) missing from the export: " + ", ".join(missing), file=sys.stderr)
        return 2
    if not drift:
        print(f"{a.slug}: no drift — all {len(man.get('nodes', {}))} node bodies match MANIFEST.")
        return 0

    for name, want, have, _ in drift:
        print(f"  ~ {name}: {want[:12]} -> {have[:12]}")
    if a.check:
        print(f"{a.slug}: {len(drift)} node body/bodies differ from MANIFEST (--check: no writes).")
        return 1

    for name, _, have, lines in drift:
        rec = man["nodes"][name]
        if isinstance(rec, dict):
            rec["sha256"], rec["lines"] = have, lines
        else:
            man["nodes"][name] = have
    # workflow.json is regenerated by assemble.py at deploy time, so its recorded hash is only
    # meaningful for an untouched export. Drop it rather than record a value that will be wrong.
    man.pop("workflow_json_sha256", None)
    man["locally_edited"] = True   # a reader (and a reviewer) can see this export is no longer pristine
    mp.write_text(json.dumps(man, indent=2, sort_keys=True) + "\n")
    print(f"{a.slug}: re-pinned {len(drift)} node hash(es). versionId left at "
          f"{man.get('versionId','?')[:8]} — still the live base this edit sits on.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
