#!/usr/bin/env python3
"""
split-uac.py — regroup the historical tests/UAC.md monolith into tests/uac/.

WHY: UAC.md is ~4,000 lines / 297 KB and every tester read or grepped all of it
to run a change touching ~200 lines. Split = §0 safety + one family file (~478
lines), the same bytes regrouped.

Idempotent. Re-run after appending new §-sections to UAC.md.
Verifies every section body survives verbatim (except §0, which gets a fuller
header in its dedicated always-read file) and refuses to write on loss.
"""
import re, pathlib, collections, sys

TESTS = pathlib.Path(__file__).resolve().parents[1] / "tests"
src = TESTS / "UAC.md"
out = TESTS / "uac"

lines = src.read_text().split("\n")
starts = [i for i, l in enumerate(lines) if re.match(r"^## §", l)]
if not starts:
    sys.exit("no '## §' sections found")

secs = []
for j, i in enumerate(starts):
    end = starts[j + 1] if j + 1 < len(starts) else len(lines)
    fam = re.match(r"^## §([A-Za-z0-9]+)", lines[i]).group(1)
    secs.append((fam, lines[i], "\n".join(lines[i:end])))

fams = collections.OrderedDict()
for fam, head, body in secs:
    fams.setdefault(fam, []).append((head, body))

out.mkdir(exist_ok=True)
(out / "00-SAFETY-always-read.md").write_text(
    "# §0 — MANDATORY safety checklist\n\n"
    "> Applies to EVERY case in every §-file. A §0 failure is a hard fail and halts the run.\n"
    "> Read this file plus ONLY the §-file for the change you are working on.\n\n"
    + fams["0"][0][1].split("\n", 1)[1].lstrip("\n"))

for fam, items in fams.items():
    if fam == "0":
        continue
    body = (f"# UAC §{fam}\n\n"
            "> ⚠️ **`00-SAFETY-always-read.md` (§0) applies to every case here.**\n\n"
            + "\n\n".join(b.rstrip() for _, b in items) + "\n")
    (out / f"{fam}.md").write_text(body)

def gist(items):
    return (re.sub(r"^## §[A-Za-z0-9.\-]*\s*[—-]?\s*", "", items[0][0]).split("(")[0].strip()[:70] or "—")

idx = ["# UAC index — read §0 + ONE file, not the 4,000-line monolith", "",
       "`00-SAFETY-always-read.md` (§0) is mandatory for every case. Then open only the §-file for your change.", "",
       "| file | sections | lines | what it covers |", "|---|---|---|---|",
       f"| `00-SAFETY-always-read.md` | §0 | {len(fams['0'][0][1].splitlines())} | **mandatory safety gate, every case** |"]
for fam, items in fams.items():
    if fam == "0":
        continue
    idx.append(f"| `{fam}.md` | §{fam} ×{len(items)} | "
               f"{sum(len(b.splitlines()) for _, b in items)} | {gist(items)} |")
idx += ["", "---", "",
        "Generated by `scripts/split-uac.py`. The monolith `../UAC.md` is kept for provenance only —",
        "these files are the same bytes, regrouped. Re-run the script after adding sections to UAC.md."]
(out / "README.md").write_text("\n".join(idx) + "\n")

blob = "".join(p.read_text() for p in out.glob("*.md"))
lost = [h for f, h, b in secs if f != "0" and b.rstrip() not in blob]
z = fams["0"][0][1].split("\n", 1)[1].strip()
assert z in blob, "§0 body not preserved"
assert not lost, f"{len(lost)} section(s) lost: {lost[:3]}"
print(f"✓ {len(secs)} sections -> {len(list(out.glob('*.md')))} files, all content preserved")
